# Generated by Django 4.1.7 on 2023-04-10 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_appuser_all_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
